/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTeacherRouteImport } from './routes/dashboard.teacher'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeacherRoute = DashboardTeacherRouteImport.update({
  id: '/dashboard/teacher',
  path: '/dashboard/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/dashboard/student',
  path: '/dashboard/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/admin'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/admin'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard/admin'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardStudentRoute: typeof DashboardStudentRoute
  DashboardTeacherRoute: typeof DashboardTeacherRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/dashboard/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardStudentRoute: DashboardStudentRoute,
  DashboardTeacherRoute: DashboardTeacherRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
