/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as DashboardTeacherRouteImport } from './routes/dashboard.teacher'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthJoinSchoolRouteImport } from './routes/auth.join-school'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthCreateSchoolRouteImport } from './routes/auth.create-school'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeacherRoute = DashboardTeacherRouteImport.update({
  id: '/dashboard/teacher',
  path: '/dashboard/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/dashboard/student',
  path: '/dashboard/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/dashboard/analytics',
  path: '/dashboard/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthJoinSchoolRoute = AuthJoinSchoolRouteImport.update({
  id: '/auth/join-school',
  path: '/auth/join-school',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreateSchoolRoute = AuthCreateSchoolRouteImport.update({
  id: '/auth/create-school',
  path: '/auth/create-school',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/create-school': typeof AuthCreateSchoolRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/join-school': typeof AuthJoinSchoolRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/create-school': typeof AuthCreateSchoolRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/join-school': typeof AuthJoinSchoolRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/create-school': typeof AuthCreateSchoolRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/join-school': typeof AuthJoinSchoolRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/student': typeof DashboardStudentRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/create-school'
    | '/auth/forgot-password'
    | '/auth/join-school'
    | '/auth/login'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/auth/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/create-school'
    | '/auth/forgot-password'
    | '/auth/join-school'
    | '/auth/login'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/auth'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth/create-school'
    | '/auth/forgot-password'
    | '/auth/join-school'
    | '/auth/login'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/auth/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCreateSchoolRoute: typeof AuthCreateSchoolRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthJoinSchoolRoute: typeof AuthJoinSchoolRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardStudentRoute: typeof DashboardStudentRoute
  DashboardTeacherRoute: typeof DashboardTeacherRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/dashboard/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/join-school': {
      id: '/auth/join-school'
      path: '/auth/join-school'
      fullPath: '/auth/join-school'
      preLoaderRoute: typeof AuthJoinSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/create-school': {
      id: '/auth/create-school'
      path: '/auth/create-school'
      fullPath: '/auth/create-school'
      preLoaderRoute: typeof AuthCreateSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCreateSchoolRoute: AuthCreateSchoolRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthJoinSchoolRoute: AuthJoinSchoolRoute,
  AuthLoginRoute: AuthLoginRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardStudentRoute: DashboardStudentRoute,
  DashboardTeacherRoute: DashboardTeacherRoute,
  AuthIndexRoute: AuthIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
